// <auto-generated />
using System;
using Fretefy.Test.Infra.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fretefy.Test.Infra.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250516004301_Update Database")]
    partial class UpdateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegiaoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoId");

                    b.ToTable("Cidade");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7978f411-3a92-4300-aaa5-59e7b939cd07"),
                            Nome = "Rio Branco",
                            Status = 0,
                            UF = "AC"
                        },
                        new
                        {
                            Id = new Guid("545b489d-892a-4baa-801f-d88f8616b458"),
                            Nome = "Maceió",
                            Status = 0,
                            UF = "AL"
                        },
                        new
                        {
                            Id = new Guid("0d0dc89d-dcd9-49f4-a460-09cedab34f48"),
                            Nome = "Macapá",
                            Status = 0,
                            UF = "AP"
                        },
                        new
                        {
                            Id = new Guid("97f489ab-b7d3-4864-bf07-47f8048dad0e"),
                            Nome = "Manaus",
                            Status = 0,
                            UF = "AM"
                        },
                        new
                        {
                            Id = new Guid("172515a0-b664-4f96-bc31-6d9f54537b89"),
                            Nome = "Salvador",
                            Status = 0,
                            UF = "BA"
                        },
                        new
                        {
                            Id = new Guid("f8b7f75f-4873-4b76-885d-9abb82b99a47"),
                            Nome = "Fortaleza",
                            Status = 0,
                            UF = " CE"
                        },
                        new
                        {
                            Id = new Guid("34aa74c9-dbce-4da1-9e6c-5497f9d96bd5"),
                            Nome = "Brasília",
                            Status = 0,
                            UF = "DF"
                        },
                        new
                        {
                            Id = new Guid("9b060d44-4785-436c-88a5-2d6fe4f520ca"),
                            Nome = "Vitória",
                            Status = 0,
                            UF = "ES"
                        },
                        new
                        {
                            Id = new Guid("dc88fff2-fc41-4205-b54e-02de56331a76"),
                            Nome = "Goiânia",
                            Status = 0,
                            UF = "GO"
                        },
                        new
                        {
                            Id = new Guid("42fa4b11-302d-4c6c-bec4-1838455e4555"),
                            Nome = "São Luís",
                            Status = 0,
                            UF = "MA"
                        },
                        new
                        {
                            Id = new Guid("432fcf69-f857-4d62-9443-190e1613b301"),
                            Nome = "Cuiabá",
                            Status = 0,
                            UF = "MT"
                        },
                        new
                        {
                            Id = new Guid("0963eb80-ce57-4480-b2d1-1b230941adec"),
                            Nome = "Campo Grande",
                            Status = 0,
                            UF = "MS"
                        },
                        new
                        {
                            Id = new Guid("e808ff35-a75a-452a-aa69-248c6b5199bd"),
                            Nome = "Belo Horizonte",
                            Status = 0,
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("db8777d1-db5b-49c3-959f-7021617a3794"),
                            Nome = "Belém",
                            Status = 0,
                            UF = "PA"
                        },
                        new
                        {
                            Id = new Guid("743214df-d5b8-416a-9a3b-5f93da3346ad"),
                            Nome = "João Pessoa",
                            Status = 0,
                            UF = "PB"
                        },
                        new
                        {
                            Id = new Guid("3569c1b8-4294-4773-92f6-7a42515cc7f1"),
                            Nome = "Curitiba",
                            Status = 0,
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("1871f583-01e2-47b5-b6a7-e737939bcb69"),
                            Nome = "Recife",
                            Status = 0,
                            UF = "PE"
                        },
                        new
                        {
                            Id = new Guid("ccc635b3-e8ea-4724-9262-77cd6063ec54"),
                            Nome = "Teresina",
                            Status = 0,
                            UF = "PI"
                        },
                        new
                        {
                            Id = new Guid("1b54fd46-8272-4103-a3ae-a67a08a7295b"),
                            Nome = "Rio de Janeiro",
                            Status = 0,
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("9d852037-f1fc-42f4-be88-617165d58fd3"),
                            Nome = "Natal",
                            Status = 0,
                            UF = "RN"
                        },
                        new
                        {
                            Id = new Guid("69c29fa5-90a8-4399-ae86-3787dd7b1f1e"),
                            Nome = "Porto Alegre",
                            Status = 0,
                            UF = "RS"
                        },
                        new
                        {
                            Id = new Guid("91db4b44-c951-4841-b2ac-230ef5c87d50"),
                            Nome = "Porto Velho",
                            Status = 0,
                            UF = "RO"
                        },
                        new
                        {
                            Id = new Guid("9d3d587f-d021-4899-abe8-002a95727027"),
                            Nome = "Boa Vista",
                            Status = 0,
                            UF = "RR"
                        },
                        new
                        {
                            Id = new Guid("4111b310-5deb-40bc-a6c1-553a774c6fc3"),
                            Nome = "Florianópolis",
                            Status = 0,
                            UF = "SC"
                        },
                        new
                        {
                            Id = new Guid("5d9aad0b-9839-4d35-bd9f-01e6e555a9d2"),
                            Nome = "São Paulo",
                            Status = 0,
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("cb50276c-4e7a-4e58-80f6-66ff397c2006"),
                            Nome = "Aracaju",
                            Status = 0,
                            UF = "SE"
                        },
                        new
                        {
                            Id = new Guid("bea97597-61a5-4c46-9b37-28cb19d4bbc7"),
                            Nome = "Palmas",
                            Status = 0,
                            UF = "TO"
                        });
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Regiao");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.RegiaoCidade", b =>
                {
                    b.Property<Guid>("CidadeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegiaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("CidadeId", "RegiaoId");

                    b.HasIndex("RegiaoId");

                    b.ToTable("RegiaoCidade");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("Fretefy.Test.Domain.Entities.Regiao", null)
                        .WithMany("Cidades")
                        .HasForeignKey("RegiaoId");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.RegiaoCidade", b =>
                {
                    b.HasOne("Fretefy.Test.Domain.Entities.Cidade", "Cidade")
                        .WithMany("RegiaoCidades")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fretefy.Test.Domain.Entities.Regiao", "Regiao")
                        .WithMany("RegiaoCidades")
                        .HasForeignKey("RegiaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("RegiaoCidades");
                });

            modelBuilder.Entity("Fretefy.Test.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("Cidades");

                    b.Navigation("RegiaoCidades");
                });
#pragma warning restore 612, 618
        }
    }
}
